/**
 * Arbitrary type automatically generated from a JSON file which was generated by converting WFS XML file.
 * Do not use it other than helping you understand the structure of WFS file turned into a JSON object.
 */
export interface WFSFeatureCollection {
  _declaration: Declaration;
  FeatureCollection: FeatureCollection1;
}
export interface Declaration {
  _attributes: Attributes;
}
export interface Attributes {
  version: string;
  encoding: string;
}
export interface FeatureCollection1 {
  _attributes: Attributes1;
  boundedBy: BoundedBy;
  featureMember?: (FeatureMemberEntity)[] | null;
}
export interface Attributes1 {
  "xmlns:mm": string;
  "xmlns:gml": string;
  "xmlns:wfs": string;
  "xmlns:xsi": string;
  "xsi:schemaLocation": string;
}
export interface BoundedBy {
  Box: BoxOrPoint;
}
export interface BoxOrPoint {
  _attributes: Attributes2;
  coordinates: CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash;
}
export interface Attributes2 {
  srsName: string;
}
export interface CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash {
  _text: string;
}
export interface FeatureMemberEntity {
  "stations_mix-obs": StationsMixObs;
}
export interface StationsMixObs {
  _attributes: Attributes3;
  Shape: Shape;
  name?: CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash1 | null;
  WMO_ID?: CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash2 | null;
  alternative_ID?: CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash3 | null;
  elevation: CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash;
  hash: CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash;
}
export interface Attributes3 {
  fid: string;
}
export interface Shape {
  Point: BoxOrPoint;
}
export interface CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash1 {
  _text: string;
}
export interface CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash2 {
  _text: string;
}
export interface CoordinatesOrNameOrWMOIDOrAlternativeIDOrElevationOrHash3 {
  _text: string;
}
